### PR TITLE
fix: fix mobile view horizontal overflow

### PR DESCRIPTION
**Pull request by ebokes**
I have fixed the horizontal overflow issue in Main page, excluding the readme file

### CODE REVIEW

**Comment by Min-Ho-Lim** [comment]
image
image

There is still overflow on the x axis on mobile view.

Also, please do not create another pull request to adapt any feedback. It makes hard for the reviewers to follow.
If you are going to make a change, work on the same pull request.

**Comment by ebokes** [comment]
I've figured out what the main issue is and I'm on it

**Comment by ebokes** [comment]
I think I have finally been able to resolve the issue

**Review by Min-Ho-Lim — APPROVED** [review]
I confirmed that the issue has been fixed. Thanks for the contribution. Approved.

**Pull request merged**
